Práctica 05: Analisis de Datos Exploratorio con Python y Jupiter Notebook

**Programa de Estudios:** Ingenieria en Desarrollo y Gestion de Softwar \
**Asignatura:** Extraccion de Conocimiento en Base de Datos \
**Docente:** M.T.I. Marco A. Ramirez Hernandez \
**Periodo:** Mayo - Agosto 2026

### Unidad 2: Preparacion de los Datos

**Nombre del Estudiante:** Jonathan Baldemar Ramírez Reyes \
**Matricula:** 230410 \
**Grado y Grupo:** 9B IDGS

El estudiante parcticara como realizar un analisis exploratorio, de datos (EDA), utilizando el lenguaje de programacion de Python, y 
librerias comunes para la carga, manipulacion, analisis y visializacion previa de un conjunto de datos (Datase), para esta practica se utilizaran las 
librerias de:

- Pandas
- Numpy
- SeAborn
- os
- Matplotlib

1. Importar las librerias nesesarias para realizar el EDA

Comenzaremos por importar la libreria que nos permitira manipulart los datos del datases extraidos de una fuente de datos (datasource)

In [11]:
import pandas  as pd
import matplotlib.pyplot as plt
import seaborn as sns

2. Creamos un DataFrame, leyendo el archivo delimitado por comas (.CSV)

In [12]:
pokemons=pd.read_csv('./Pokemon_with_evolution.csv')

3. Imprime en una tabla las columnas y las filas del dataframe, siempre de manera estandar nos mostrara los primeros 5 y los ultimos 5 registros 
del dataframe

In [13]:
pokemons

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Evolution_Level
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,2
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,3
3,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,3
4,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,722,Chiplet,Artificial,Electric,320,50,45,55,70,50,50,7,False,1
806,723,Circuiton,Artificial,Electric,450,70,65,75,95,70,75,7,False,2
807,724,Mechadra,Artificial,Dragon,610,95,110,100,120,90,95,7,False,3
808,725,MegaMechadra,Artificial,Dragon,750,110,145,130,150,110,105,7,False,4
809,726,Quantox,Artificial,Psychic,680,100,90,95,145,120,130,7,True,1

4. Imprime en una tabla las columnas y las filas del dataframe, siempre de manera estandar nos mostrara los primeros 50 registros del dataframe

In [14]:
pokemons.head(50)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Evolution_Level
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,2
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,3
3,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,3
4,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,4
5,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1
6,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,2
7,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,3
8,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,4
9,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,4
10,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,1
11,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,2
12,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,3
13,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,4
14,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,1
15,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,2
16,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False,3
17,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1
18,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,2
19,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,3
20,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,4
21,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False,1
22,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False,2
23,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False,3
24,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,4
25,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False,1
26,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False,2
27,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False,1
28,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False,2
29,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False,1
30,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False,2
31,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False,1
32,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False,2
33,27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False,1
34,28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,1,False,2
35,29,Nidoran♀,Poison,NaN,275,55,47,52,40,40,41,1,False,1
36,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False,2
37,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False,3
38,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False,1
39,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False,2
40,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False,3
41,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False,1
42,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False,2
43,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False,1
44,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False,2
45,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False,1
46,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False,2
47,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False,1
48,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False,2
49,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False,1

5. Obtener una muestra de rangos definidos usando **.lloc**

In [15]:
pokemons_100_to_200 = pokemons.iloc[100:200]
pokemons_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Evolution_Level
100,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False,2
101,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False,1
102,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False,2
103,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False,3
104,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,179,Mareep,Electric,NaN,280,55,40,40,65,45,35,2,False,1
196,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False,2
197,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False,3
198,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False,4
199,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False,2

6. Como saber las columnas o atributos que tiene el DataFrame

In [16]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary',
       'Evolution_Level'],
      dtype='object')

| Campo | Descripción |
|---|---|
| **#** | El ID o número de identificación del Pokémon. |
| **Name** | El nombre del Pokémon. |
| **Type 1** | Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos. |
| **Type 2** | Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo Dual); los movimientos solo pueden tener uno. |
| **Total** | Representa la suma de todos los stats, lo que te da una idea de qué tan "pesado" o fuerte es el Pokémon. |
| **HP** | (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye). |
| **Attack** | La fuerza de los ataques físicos del Pokémon. |
| **Defense** | Qué tanto aguanta el Pokémon contra los ataques físicos del rival. |
| **Evolution_Level** | Nivel de Evolución del Pokémon. |
| **Sp. Atk** | Ataque Especial: el poder de los movimientos especiales del Pokémon. |
| **Sp. Def** | Defensa Especial: Qué tan resistente es el Pokémon ante los ataques especiales. |
| **Speed** | Velocidad; el Pokémon que tenga más velocidad es el que ataca primero. |
| **Generation** | Generación: Se refiere a la generación de la serie de juegos a la que pertenece. |
| **Legendary** | Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano (sí/no). |

7. Explorar la composicion y ausencia de datos (METADATA) con **.info**

In [17]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   #                810 non-null    int64
 1   Name             810 non-null    object
 2   Type 1           810 non-null    object
 3   Type 2           421 non-null    object
 4   Total            810 non-null    int64
 5   HP               810 non-null    int64
 6   Attack           810 non-null    int64
 7   Defense          810 non-null    int64
 8   Sp. Atk          810 non-null    int64
 9   Sp. Def          810 non-null    int64
 10  Speed            810 non-null    int64
 11  Generation       810 non-null    int64
 12  Legendary        810 non-null    bool
 13  Evolution_Level  810 non-null    int64
dtypes: bool(1), int64(10), object(3)
memory usage: 83.2+ KB

8. Limpieza de datos

Dependiendo del objeto del analisis algunas columnas o registros no seran nesesarias en neutro Dataframe, en este caso omitiremos los datos vacios, por lo que eliminaremos la colimna **Type2** y renombraremos la columna **Type1** por **Type**.

In [18]:
del pokemons['Type 2']
pokemons.rename(columns={'Type 1': 'Type'}, inplace = True )

**Ejercicios 2** Consulta la metadata de la actualizacion y compar los cambios con la anterior.
¿Que cambios ves? Redacta tu respuesta:

In [19]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 810 entries, 0 to 809
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   #                810 non-null    int64
 1   Name             810 non-null    object
 2   Type             810 non-null    object
 3   Total            810 non-null    int64
 4   HP               810 non-null    int64
 5   Attack           810 non-null    int64
 6   Defense          810 non-null    int64
 7   Sp. Atk          810 non-null    int64
 8   Sp. Def          810 non-null    int64
 9   Speed            810 non-null    int64
 10  Generation       810 non-null    int64
 11  Legendary        810 non-null    bool
 12  Evolution_Level  810 non-null    int64
dtypes: bool(1), int64(10), object(2)
memory usage: 76.9+ KB

**Cambios:** La cantidad de columnas bajó de 14 a 13 porque se eliminó la columna Type 2. También la columna Type 1 fue renombrada a simplemente Type,

9. Visualizacion de los primeros datos usando el metodo **.head**

In [20]:
pokemons.head(50)

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Evolution_Level
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False,2
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False,3
3,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False,3
4,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False,4
5,4,Charmander,Fire,309,39,52,43,60,50,65,1,False,1
6,5,Charmeleon,Fire,405,58,64,58,80,65,80,1,False,2
7,6,Charizard,Fire,534,78,84,78,109,85,100,1,False,3
8,6,CharizardMega Charizard X,Fire,634,78,130,111,130,85,100,1,False,4
9,6,CharizardMega Charizard Y,Fire,634,78,104,78,159,115,100,1,False,4
10,7,Squirtle,Water,314,44,48,65,50,64,43,1,False,1
11,8,Wartortle,Water,405,59,63,80,65,80,58,1,False,2
12,9,Blastoise,Water,530,79,83,100,85,105,78,1,False,3
13,9,BlastoiseMega Blastoise,Water,630,79,103,120,135,115,78,1,False,4
14,10,Caterpie,Bug,195,45,30,35,20,20,45,1,False,1
15,11,Metapod,Bug,205,50,20,55,25,25,30,1,False,2
16,12,Butterfree,Bug,395,60,45,50,90,80,70,1,False,3
17,13,Weedle,Bug,195,40,35,30,20,20,50,1,False,1
18,14,Kakuna,Bug,205,45,25,50,25,25,35,1,False,2
19,15,Beedrill,Bug,395,65,90,40,45,80,75,1,False,3
20,15,BeedrillMega Beedrill,Bug,495,65,150,40,15,80,145,1,False,4
21,16,Pidgey,Normal,251,40,45,40,35,35,56,1,False,1
22,17,Pidgeotto,Normal,349,63,60,55,50,50,71,1,False,2
23,18,Pidgeot,Normal,479,83,80,75,70,70,101,1,False,3
24,18,PidgeotMega Pidgeot,Normal,579,83,80,80,135,80,121,1,False,4
25,19,Rattata,Normal,253,30,56,35,25,35,72,1,False,1
26,20,Raticate,Normal,413,55,81,60,50,70,97,1,False,2
27,21,Spearow,Normal,262,40,60,30,31,31,70,1,False,1
28,22,Fearow,Normal,442,65,90,65,61,61,100,1,False,2
29,23,Ekans,Poison,288,35,60,44,40,54,55,1,False,1
30,24,Arbok,Poison,438,60,85,69,65,79,80,1,False,2
31,25,Pikachu,Electric,320,35,55,40,50,50,90,1,False,1
32,26,Raichu,Electric,485,60,90,55,90,80,110,1,False,2
33,27,Sandshrew,Ground,300,50,75,85,20,30,40,1,False,1
34,28,Sandslash,Ground,450,75,100,110,45,55,65,1,False,2
35,29,Nidoran♀,Poison,275,55,47,52,40,40,41,1,False,1
36,30,Nidorina,Poison,365,70,62,67,55,55,56,1,False,2
37,31,Nidoqueen,Poison,505,90,92,87,75,85,76,1,False,3
38,32,Nidoran♂,Poison,273,46,57,40,40,40,50,1,False,1
39,33,Nidorino,Poison,365,61,72,57,55,55,65,1,False,2
40,34,Nidoking,Poison,505,81,102,77,85,75,85,1,False,3
41,35,Clefairy,Fairy,323,70,45,48,60,65,35,1,False,1
42,36,Clefable,Fairy,483,95,70,73,95,90,60,1,False,2
43,37,Vulpix,Fire,299,38,41,40,50,65,65,1,False,1
44,38,Ninetales,Fire,505,73,76,75,81,100,100,1,False,2
45,39,Jigglypuff,Normal,270,115,45,20,45,25,20,1,False,1
46,40,Wigglytuff,Normal,435,140,70,45,85,50,45,1,False,2
47,41,Zubat,Poison,245,40,45,35,30,40,55,1,False,1
48,42,Golbat,Poison,455,75,80,70,65,75,90,1,False,2
49,43,Oddish,Grass,320,45,50,55,75,65,30,1,False,1